---
title: "Course 1: Train / Validation / Test Split"
author: "Paul"
date: "26 November 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Packages

```{r}
install.packages('dplyr')
library(dplyr)
```

#Data set

```{r}
df<- dplyr::tibble(x=1:1000)
```

##Train , Validation, Test set split

```{r}
set.seed(123)
train_ratio<-0.6
validation_ratio=0.2
test_ratio<-1-train_ratio-validation_ratio
```

```{r}
set.seed(123)
n_obs<- nrow(df)
sample_size_train<- floor(train_ratio * n_obs)
sample_size_valid<- floor(validation_ratio*n_obs)
sample_size_test<- floor(test_ratio*n_obs)
#floor: round integer to lower full number

indices_train <- sort(base::sample(x=1:n_obs,size=sample_size_train))

indices_not_train <- setdiff(1:n_obs, indices_train)

indices_validation <- sort(base::sample(indices_not_train, size=sample_size_valid))
indices_test<- setdiff(indices_not_train, indices_validation)

train<- df[indices_train, ]
val<- df[indices_validation,]
test<- df[indices_test,]
```

