---
title: "Course3_SVM"
author: "Paul"
date: "6 Dezember 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(e1071)
library(keras)
library(caret)
source('./train_val_test_split.R')
```

```{r}
set.seed(123)
df <- tibble(x=runif(n=2000, min = -10, max = 10),
             y =runif(n=2000, min = -10, max = 10)) %>%
  
  mutate(z=x^2 + y^2) %>%
  mutate(class = ifelse(z < 50, 'A', 'B')) %>%
  mutate(class=as.factor(class))
```

```{r}
g <- ggplot(df, aes(x, y, col = class))
g <- g + geom_point()
g
```

# DF split

```{r}
set.seed(123)
c(train, val, test) %<-% train_val_test_split(df, train_ratio =0.8, val_ratio = 0.2, test_ratio = 0.0)
```

# Model

```{r}
model_svm <- svm(data= train, class ~ x + y, kernel = 'radial')
```

```{r}
plot(model_svm, train, y ~ x)
```


# Predictions

```{r}
val$class_pred <- predict(model_svm, newdata = val)
```


# Confusion Matrix

```{r}
cm_val <- table(pred = val$class_pred, obs=val$class)
cm_val
```

```{r}
confusionMatrix(val$class_pred, val$class)
```

# Hyperparameter

You could modify

- kernel

- cost value

- gama

```{r}
model_svm <- svm(data=train, class ~ x + y, kernel = 'radial', gamma = 12, cost = 2000)
val$class_pred <- predict(model_svm, val)
confusionMatrix(val$class_pred, val$class)
```

